# this alternative is used for new infomation, not those that are passed from the Osemosys database.
default_alternative: "base"

unlimited_unit_capacity: 100000 #MW
default_unit_size: 10   #MW
unit_to_penalty_boundary: 99999 #MW
default_interest_rate: 0.07 # if not specified in the OSeMOSYS data

#all units are converted to MW, MWh, CUR/MW or CUR/MWh. 
#Some are presented as annual values in OSEMOSYS. factor to power and factor to hour are both included here.
capacity_unit_to_MW_factor: 1000
storage_capacity_unit_to_MWh_factor: 8.76
demand_unit_to_MWh_factor: 31536
investment_unit_to_CUR/MW_factor: 1000
storage_investment_unit_to_CUR/MWh_factor: 1000
variable_cost_unit_to_CUR/MW_factor: 1000


# For example if the units in OSEMOSYS are: 
#	Energy and demands in PJ/a
#	Power plants in GW
#	Investment and Fixed O&M Costs: Power plant: Million $ / GW (//$/kW)
#	Other plant costs: Million $/PJ/a
#	Variable O&M (& Import) Costs: Million $ / PJ (//$/GJ)

# Then the factors are:
#capacity_unit_to_MW_factor: 1000
#storage_capacity_unit_to_MWh_factor: 8.76
#demand_unit_to_MWh_factor: 31536
#investment_unit_to_CUR/MW_factor: 1000
#storage_investment_unit_to_CUR/MWh_factor: 1000
#variable_cost_unit_to_CUR/MW_factor: 1000